### ISSUE TITLE
Add generate command

### ISSUE THREAD

**Issue by pythonhubdev** [pythonhubdev/faag_cli#1]
Instead of running `faag` solely without specifying any argument leads to confusion. Instead add a generate command which can generate the app. If no argument is specified show the `help` or a description on how to use the CLI

**Comment by pravincoder** [comment]
i can do this @pythonhubdev

**Comment by pythonhubdev** [comment]
Sorry, @pravincoder I have started on this already. Please watch and star the repository. There are many features to be added so you can surely contribute to upcoming features. I will add the road map in a day or two. Thanks for taking the time to contribute. Meanwhile, you can fork and have a look at the repo and understand the code base also feel free to add suggestions.

**Comment by pravincoder** [comment]
No Problem! @pythonhubdev I might help you in future !
